name       : openimageio
version    : 1.5.16
release    : 3
source     :
    - https://github.com/OpenImageIO/oiio/archive/Release-1.5.16.tar.gz : 6c676ae5ddc3b2a8f8d37b521c670d8b3f82d1af583801027d44cf61e1550d6b
license    : BSD-3-Clause
summary    : OpenImageIO
description: |
    The primary target audience for OIIO is VFX studios and developers of tools such as renderers, compositors, viewers, and other image-related software you'd find in a production pipeline.
builddeps  :
    - pkgconfig(libtiff-4)
    - pkgconfig(OpenColorIO)
    - pkgconfig(OpenEXR)
    - pkgconfig(libpng)
    - pkgconfig(libwebp)
    - pkgconfig(libraw1394)
    - libboost-devel
    - libjpeg-turbo-devel
clang      : no
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
