name       : openimageio
version    : 1.8.8
release    : 14
source     :
    - https://github.com/OpenImageIO/oiio/archive/Release-1.8.8.tar.gz : d7d529f1318b2ac8325f18b94f017d4d0bf878731178afb72eb5e75642873dc5
homepage   : http://www.openimageio.org/
license    : BSD-3-Clause
component  : multimedia.library
summary    : OpenImageIO
description: |
    The primary target audience for OIIO is VFX studios and developers of tools such as renderers, compositors, viewers, and other image-related software you'd find in a production pipeline.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libwebp)
    - pkgconfig(OpenColorIO)
    - pkgconfig(OpenEXR)
    - pkgconfig(libopenjp2)
    - pkgconfig(libraw)
    - bzip2-devel
    - libboost-devel
setup      : |
    export CFLAGS="$CFLAGS $(pkg-config libraw --cflags)"
    mkdir build && cd build
    %cmake .. -DUSE_CPP=14 \
        -DINSTALL_FONTS=FALSE \
        -DUSE_OPENSSL=TRUE \
        -DOPENJPEG_INCLUDE_DIR=$(pkg-config libopenjp2 --variable=includedir)
build      : |
    export CFLAGS="$CFLAGS $(pkg-config libraw --cflags)"
    %make -C build
install    : |
    export CFLAGS="$CFLAGS $(pkg-config libraw --cflags)"
    %make_install -C build
