name       : openimageio
version    : 2.3.10.1
release    : 36
source     :
    - https://github.com/OpenImageIO/oiio/archive/refs/tags/v2.3.10.1.tar.gz : 3b83d2329c5f1d771773ba149d4292b13492cbbc8a936fab63502372d8603995
homepage   : https://openimageio.readthedocs.io/
license    : BSD-3-Clause
component  : multimedia.library
summary    : OpenImageIO
description: |
    The primary target audience for OIIO is VFX studios and developers of tools such as renderers, compositors, viewers, and other image-related software you'd find in a production pipeline.
builddeps  :
    - pkgconfig(OpenColorIO)
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Core)
    - pkgconfig(fmt)
    - pkgconfig(freetype2)
    - pkgconfig(hdf5)
    - pkgconfig(libavcodec)
    - pkgconfig(libheif)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libwebp)
    - pkgconfig(pugixml)
    - pkgconfig(python3)
    - bzip2-devel
    - giflib-devel
    - git
    - intel-tbb-devel
    - libboost-devel
    - openvdb-devel
    - ptex-devel
    - pybind11
    - robin-map
rundeps    :
    - devel :
        - openexr-devel
        - opencolorio-devel
setup      : |
    %patch -p1 < $pkgfiles/disable-tests-completely.patch
    %cmake_ninja \
      -DBUILD_MISSING_PYBIND11=OFF \
      -DOIIO_BUILD_TESTS=OFF \
      -DCMAKE_CXX_STANDARD=17 \
      -DINSTALL_FONTS=FALSE \
      -DUSE_PYTHON=ON \
      -DUSE_EXTERNAL_PUGIXML=ON \
      -DSTOP_ON_WARNING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
