name       : openimageio
version    : 1.6.18
homepage   : http://www.openimageio.org/
release    : 7
source     :
    - https://github.com/OpenImageIO/oiio/archive/Release-1.6.18.tar.gz : 36b592bb6eda9dd18a9e1a86668cfec6e2827d792965f51a09223359d5d1bbfd
license    : BSD-3-Clause
component  : multimedia.library
summary    : OpenImageIO
description: |
    The primary target audience for OIIO is VFX studios and developers of tools such as renderers, compositors, viewers, and other image-related software you'd find in a production pipeline.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(libraw1394)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(OpenColorIO)
    - pkgconfig(OpenEXR)
    - libboost-devel
    - libjpeg-turbo-devel
setup      : |
    mkdir build && cd build
    %cmake ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
