name       : openimageio
version    : 2.2.10.1
release    : 20
source     :
    - https://github.com/OpenImageIO/oiio/archive/v2.2.10.1.tar.gz : 66408e4e1959c0f7b3dabfa9e9ae682c6fdff34c892434b6e201bd5c969bcbe1
homepage   : http://www.openimageio.org/
license    : BSD-3-Clause
component  : multimedia.library
summary    : OpenImageIO
description: |
    The primary target audience for OIIO is VFX studios and developers of tools such as renderers, compositors, viewers, and other image-related software you'd find in a production pipeline.
builddeps  :
    - pkgconfig(OpenColorIO)
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Core)
    - pkgconfig(fmt)
    - pkgconfig(freetype2)
    - pkgconfig(libavcodec)
    - pkgconfig(libheif)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libwebp)
    - pkgconfig(pugixml)
    - pkgconfig(python3)
    - bzip2-devel
    - giflib-devel
    - intel-tbb-devel
    - libboost-devel
    - openvdb-devel
    - pybind11
    - robin-map
setup      : |
    %patch -p1 < $pkgfiles/disable-tests-completely.patch
    %cmake_ninja .. \
      -DOIIO_BUILD_TESTS=OFF \
      -DUSE_CPP=14 \
      -DINSTALL_FONTS=FALSE \
      -DUSE_PYTHON=ON \
      -DUSE_EXTERNAL_PUGIXML=ON \
      -DSTOP_ON_WARNING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
